### ISSUE TITLE
We're not updating all Markdown files which reference `renovate/renovate` docker tags

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/.github#31]
The latest "update references to `renovate/renovate`" PR [^pr] did not update the references to `renovate/renovate` docker tags in the `docs/usage/examples/self-hosting.md` [^self-hosting] file.

Example of a reference that was missed: [^self-hosting]:

> ### Docker
> 
> Renovate is available for Docker via an automated build [renovate/renovate](https://hub.docker.com/r/renovate/renovate/).
> It builds `latest` based on the `main` branch and all semver tags are published too.
> For example, all the following are valid tags:
> 
> ```sh
> docker run --rm renovate/renovate
> docker run --rm renovate/renovate:25.69.4
> docker run --rm renovate/renovate:25.69
> docker run --rm renovate/renovate:25
> ```

Here is the Renovate configuration that applies to the created PR:

https://github.com/renovatebot/.github/blob/1cfabab3839113ac37eacb27605cb26757db5eeb/default.json#L46-L58

I'm not sure what we need to change to get this working?

[^self-hosting]: https://github.com/renovatebot/renovate/blob/main/docs/usage/examples/self-hosting.md
[^pr]: https://github.com/renovatebot/renovate/pull/12911

**Comment by viceice** [comment]
It's this regex manager:
https://github.com/renovatebot/.github/blob/main/default.json#L100-L108

I think we have a bug, when multiple different versions are updated.

**Comment by rarkins** [comment]
Not sure we ever use the sha in docs? We could maybe simplify the regex

**Comment by viceice** [comment]
I don't think it's the regex. I think renovate fails to update with auto replace

**Comment by astellingwerf** [comment]
I didn't reconstruct a full timeline for the introduction of this issue, but I think I figured this out.

We're hoping to see a change on the file with the path `docs/usage/examples/self-hosting.md`. But that path means that it is subject to exclusion from renovation due to [`:ignoremodulesandtests`](https://docs.renovatebot.com/presets-default/#ignoremodulesandtests). That preset is part of the `config:base` preset, which in turn is referenced on https://github.com/renovatebot/.github/blob/b0c3aa85ef2bb242580f20b02b380ca532b4ce17/default.json#L5

**Comment by astellingwerf** [comment]
That sorta means that this issue is dependent on https://github.com/renovatebot/renovate/issues/11159, because the preset is set on the global level, meaning that today there is no way for `ignorePresets` to undo that.

**Comment by viceice** [comment]
> That sorta means that this issue is dependent on https://github.com/renovatebot/renovate/issues/11159, because the preset is set on the global level, meaning that today there is no way for `ignorePresets` to undo that.

i don't think that issue blocks this. we don't use any global config option in our presets.

**Comment by astellingwerf** [comment]
> i don't think that issue blocks this. we don't use any global config option in our presets.

I think you're right @viceice, there was some confusion on my end on how `ignorePreset` doesn't work under certain conditions. It seems that they can't be applied on the package rule level. So I guess that if you want to exclude it on one package rule, you'll need to ignore the preset on the repo level, and then extend it on all except one package rule?
